# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setSpacing(6)
        self.topLayout.setObjectName("topLayout")
        self.runButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.runButton.setStyleSheet("#runButton {\n"
"    background-color: green;\n"
"    color: white;\n"
"}\n"
"\n"
"#runButton:disabled {\n"
"    background-color: gray;\n"
"    color: lightgray;\n"
"}")
        self.runButton.setObjectName("runButton")
        self.topLayout.addWidget(self.runButton)
        self.saveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.topLayout.addWidget(self.saveButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.topLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.topLayout)
        self.centralLayout = QtWidgets.QHBoxLayout()
        self.centralLayout.setObjectName("centralLayout")
        self.treeView = QtWidgets.QTreeView(parent=self.centralwidget)
        self.treeView.setObjectName("treeView")
        self.centralLayout.addWidget(self.treeView)
        self.filesTab = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.filesTab.setTabsClosable(True)
        self.filesTab.setObjectName("filesTab")
        self.centralLayout.addWidget(self.filesTab)
        self.centralLayout.setStretch(0, 1)
        self.centralLayout.setStretch(1, 3)
        self.verticalLayout.addLayout(self.centralLayout)
        self.bottomLayout = QtWidgets.QHBoxLayout()
        self.bottomLayout.setObjectName("bottomLayout")
        self.staticConfigLabel = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.staticConfigLabel.sizePolicy().hasHeightForWidth())
        self.staticConfigLabel.setSizePolicy(sizePolicy)
        self.staticConfigLabel.setObjectName("staticConfigLabel")
        self.bottomLayout.addWidget(self.staticConfigLabel)
        self.configStatusLabel = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configStatusLabel.sizePolicy().hasHeightForWidth())
        self.configStatusLabel.setSizePolicy(sizePolicy)
        self.configStatusLabel.setWordWrap(True)
        self.configStatusLabel.setObjectName("configStatusLabel")
        self.bottomLayout.addWidget(self.configStatusLabel)
        self.bottomLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.bottomLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 21))
        self.menubar.setObjectName("menubar")
        self.menuFRAg = QtWidgets.QMenu(parent=self.menubar)
        self.menuFRAg.setObjectName("menuFRAg")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFRAg.menuAction())

        self.retranslateUi(MainWindow)
        self.filesTab.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FRAg"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.staticConfigLabel.setText(_translate("MainWindow", "Active configuration:"))
        self.configStatusLabel.setText(_translate("MainWindow", "Configuration path"))
        self.menuFRAg.setTitle(_translate("MainWindow", "FRAg"))
